#!/bin/bash



echo "set -g fish_prompt_pwd_dir_length 0" | tee ~/.config/fish/config.fish
echo -e "function fish_user_key_bindings\n\tbind --preset ',' forward-char\nend" | tee -a ~/.config/fish/config.fish
echo -e ". ls_colors.fish" | tee -a ~/.config/fish/config.fish
echo -e "alias ls='ls --color=always'" | tee -a ~/.config/fish/config.fish

cat ls_colors.fish | tee ~/.config/fish/ls_colors.fish



